/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Backup */
        post: operations["admin_backup_api_admin_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Workers */
        get: operations["admin_workers_api_admin_workers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Endpoints */
        get: operations["get_endpoints_api_catalog_endpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Catalog */
        post: operations["refresh_catalog_api_catalog_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Favorite */
        put: operations["put_favorite_api_favorites_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instance */
        get: operations["get_instance_api_instances__instance_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instance_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay */
        get: operations["get_replay_api_instances__instance_id__replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Detail */
        get: operations["get_model_detail_api_models_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Packs */
        get: operations["get_packs_api_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pack */
        get: operations["get_pack_api_packs__pack_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practice */
        get: operations["list_practice_api_practice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/{instance_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Practice Submit */
        post: operations["practice_submit_api_practice__instance_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profiles */
        get: operations["get_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate Run */
        post: operations["estimate_run_api_runs_estimate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/actions/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Action */
        post: operations["run_action_api_runs__run_id__actions__action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-sent events. Resume with the ``Last-Event-ID`` header (or ``?after=``). Without either,
         *     the stream starts with a ``snapshot`` event carrying the current run summary.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run */
        get: operations["export_run_api_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Items */
        get: operations["get_items_api_runs__run_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/items/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_runs__run_id__items__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/reevaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reevaluate Run */
        get: operations["reevaluate_run_api_runs__run_id__reevaluate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionBody */
        ActionBody: {
            /** Value */
            value?: number | null;
        };
        /** Catalog */
        Catalog: {
            /** Errors */
            errors: {
                [key: string]: string;
            };
            /** Favorites */
            favorites: string[];
            /** Models */
            models: components["schemas"]["CatalogModel"][];
            /** Recents */
            recents: string[];
            /** Snapshots */
            snapshots: {
                [key: string]: components["schemas"]["SnapshotInfo"];
            };
        };
        /** CatalogModel */
        CatalogModel: {
            /** Compat */
            compat?: components["schemas"]["Compat"][];
            /** Context Length */
            context_length: number | null;
            /** Description */
            description: string;
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /** Is Mock */
            is_mock: boolean;
            /** Max Completion Tokens */
            max_completion_tokens: number | null;
            /** Model Id */
            model_id: string;
            /** Name */
            name: string;
            /** Pricing */
            pricing: {
                [key: string]: number | null;
            };
            /** Pricing Known */
            pricing_known: boolean;
            /** Provider */
            provider: string;
            /** Reasoning */
            reasoning: {
                [key: string]: unknown;
            } | null;
            /** Supported Parameters */
            supported_parameters: string[];
        };
        /** Compat */
        Compat: {
            /** Compatible */
            compatible: boolean;
            /** Problems */
            problems: string[];
            /** Profile Id */
            profile_id: string;
            /** Warnings */
            warnings: string[];
        };
        /** Consistency */
        Consistency: {
            /** Model Matches Request */
            model_matches_request: boolean | null;
            /** Observed Models */
            observed_models: string[];
            /** Observed Providers */
            observed_providers: string[];
            /** Provider Matches Pin */
            provider_matches_pin: boolean | null;
            /** Provider Unreported On Some Responses */
            provider_unreported_on_some_responses: boolean;
        };
        /** CostSummary */
        CostSummary: {
            /** Estimated Cost Attempts */
            estimated_cost_attempts: number;
            /** Pricing */
            pricing: {
                [key: string]: number | null;
            };
            /** Pricing Known */
            pricing_known: boolean;
            /** Reserved Usd */
            reserved_usd: number;
            /** Spend Limit Usd */
            spend_limit_usd: number;
            /** Spent Usd */
            spent_usd: number;
            /** Uncertain Cost Attempts */
            uncertain_cost_attempts: number;
        };
        /** Endpoint */
        Endpoint: {
            /** Compat */
            compat?: components["schemas"]["Compat"][];
            /** Context Length */
            context_length: number | null;
            /** Max Completion Tokens */
            max_completion_tokens: number | null;
            /** Pricing */
            pricing: {
                [key: string]: number | null;
            };
            /** Provider Name */
            provider_name: string;
            /** Quantization */
            quantization: string | null;
            /** Slug */
            slug: string;
            /** Status */
            status: number | null;
            /** Supported Parameters */
            supported_parameters: string[];
        };
        /** Endpoints */
        Endpoints: {
            /** Endpoints */
            endpoints: components["schemas"]["Endpoint"][];
            /** Error */
            error: string | null;
            /** Model Id */
            model_id: string;
        };
        /** Estimate */
        Estimate: {
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            };
            /** Calls */
            calls: number;
            /** Max Per Call Usd */
            max_per_call_usd: number | null;
            /** Pricing Known */
            pricing_known: boolean;
            /** Typical Usd */
            typical_usd: number | null;
            /** Worst Case Usd */
            worst_case_usd: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstanceSummary */
        InstanceSummary: {
            /** Budget */
            budget?: number | null;
            /** Editable */
            editable?: number | null;
            /** Entrances */
            entrances?: number | null;
            /** Instance Id */
            instance_id: string;
            /** Ord */
            ord: number;
            /** Pack Id */
            pack_id: string;
            /** Tier */
            tier: string;
            /** Tokens Max */
            tokens_max?: number | null;
        };
        /** LatencySummary */
        LatencySummary: {
            /** Mean */
            mean: number | null;
            /** Median */
            median: number | null;
            /** N */
            n: number;
        };
        /** Leaderboard */
        Leaderboard: {
            /** Listing Policy */
            listing_policy: string;
            /** Profile Id */
            profile_id: string | null;
            /** Rows */
            rows: components["schemas"]["LeaderboardRow"][];
            /** Suite */
            suite: {
                [key: string]: unknown;
            };
            /** Track */
            track: string;
        };
        /** LeaderboardRow */
        LeaderboardRow: {
            /** Completed */
            completed: number;
            /** Conditional Quality */
            conditional_quality: number | null;
            /** Cost Usd */
            cost_usd: number;
            /** Endpoint */
            endpoint: string | null;
            /** Evaluated At */
            evaluated_at: string | null;
            /** Interval 95 */
            interval_95: number[] | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            /** Optimal Rate */
            optimal_rate: number | null;
            /** Overall */
            overall: number | null;
            /** Pack Hash */
            pack_hash: string;
            /** Pack Id */
            pack_id: string;
            /** Profile Id */
            profile_id: string;
            /** Provider Name */
            provider_name: string | null;
            /** Rank */
            rank: number;
            /** Run Id */
            run_id: string;
            /** Runs In Group */
            runs_in_group: number;
            /** Scheduled */
            scheduled: number;
            /** Shadow Twins */
            shadow_twins: number | null;
            /** Suite Version */
            suite_version: string;
            /** Tiers */
            tiers: {
                [key: string]: number;
            };
            /** Track */
            track: string;
            /** Valid Rate */
            valid_rate: number | null;
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** Meta */
        Meta: {
            /** Api Version */
            api_version: string;
            /** Auth */
            auth: {
                [key: string]: unknown;
            };
            /** Benchmarks */
            benchmarks: {
                [key: string]: unknown;
            }[];
            /** Modes */
            modes: {
                [key: string]: unknown;
            }[];
            /** Packs */
            packs: components["schemas"]["PackSummary"][];
            /** Profiles */
            profiles: components["schemas"]["Profile"][];
            /** Providers */
            providers: {
                [key: string]: unknown;
            };
            /** Suite */
            suite: {
                [key: string]: unknown;
            };
        };
        /** ModelDetail */
        ModelDetail: {
            /** Categories */
            categories: {
                [key: string]: number;
            };
            /** Latest Eligible */
            latest_eligible: components["schemas"]["RunSummary"][];
            /** Model */
            model?: {
                [key: string]: unknown;
            } | null;
            /** Model Id */
            model_id: string;
            /** Runs */
            runs: components["schemas"]["ModelRun"][];
            /** Score Histogram */
            score_histogram?: {
                [key: string]: unknown;
            } | null;
            /** Usage */
            usage?: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelRun */
        ModelRun: {
            /** Completed At */
            completed_at: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Created At */
            created_at: string;
            /** Endpoint */
            endpoint: string | null;
            /** Fingerprint */
            fingerprint: string;
            /** Ineligible Reasons */
            ineligible_reasons: string[];
            /** Is Mock */
            is_mock: boolean;
            /** Leaderboard Eligible */
            leaderboard_eligible: boolean;
            /** Optimal Rate */
            optimal_rate: number | null;
            /** Overall */
            overall: number | null;
            /** Profile Id */
            profile_id: string;
            /** Provisional Overall */
            provisional_overall: number | null;
            /** Ranked */
            ranked: boolean;
            /** Run Id */
            run_id: string;
            /** State */
            state: string;
            /** Track */
            track: string;
            /** Valid Rate */
            valid_rate: number | null;
        };
        /** PackSummary */
        PackSummary: {
            /** Benchmark Id */
            benchmark_id: string;
            /** Instances */
            instances: number;
            /** Pack Hash */
            pack_hash: string;
            /** Pack Id */
            pack_id: string;
            /** Policy Hash */
            policy_hash: string | null;
            /** Ranked */
            ranked: boolean;
            /** Split */
            split: string;
            /** Tiers */
            tiers: {
                [key: string]: unknown;
            }[];
            /** Token Max */
            token_max: number | null;
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** PracticeSubmit */
        PracticeSubmit: {
            /** Add */
            add: number[];
            /** Remove */
            remove: number[];
        };
        /** Profile */
        Profile: {
            /** Description */
            description: string;
            /** Enforcement */
            enforcement: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Max Tokens */
            max_tokens: number;
            /** Reasoning */
            reasoning: {
                [key: string]: unknown;
            } | null;
            /** Requires */
            requires: string[];
            /** Temperature */
            temperature: number | null;
            /** Version */
            version: string;
        };
        /** RunCreate */
        RunCreate: {
            /**
             * Allow Unknown Pricing
             * @description Explicit unranked override to dispatch when model pricing is unknown.
             * @default false
             */
            allow_unknown_pricing: boolean;
            /**
             * Concurrency
             * @default 2
             */
            concurrency: number;
            mode: components["schemas"]["RunMode"];
            /** Model Id */
            model_id: string;
            /** Note */
            note?: string | null;
            /**
             * Pack Id
             * @description Defaults to the loaded pack for the mode.
             */
            pack_id?: string | null;
            /** Profile Id */
            profile_id: string;
            /**
             * Provider
             * @description Pinned provider endpoint slug, where supported.
             */
            provider?: string | null;
            /** Spend Limit Usd */
            spend_limit_usd: number;
        };
        /** RunItem */
        RunItem: {
            /** Attempts */
            attempts: number;
            /** Category */
            category: string | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Instance Id */
            instance_id: string;
            /** Job Id */
            job_id: number;
            /** Last Error */
            last_error: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Max Objective */
            max_objective: number | null;
            /** Ord */
            ord: number;
            /** Raw Objective */
            raw_objective: number | null;
            /** Repetition */
            repetition: number;
            /** Score */
            score: number | null;
            /** State */
            state: string;
            /** Tier */
            tier: string;
            /** Valid */
            valid: boolean | null;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "quick_check" | "standard" | "repeated";
        /** RunPlan */
        RunPlan: {
            /** Blocking */
            blocking: string[];
            compatibility: components["schemas"]["Compat"];
            /** Endpoint */
            endpoint: {
                [key: string]: unknown;
            } | null;
            /** Endpoint Error */
            endpoint_error: string | null;
            estimate: components["schemas"]["Estimate"];
            /** Mode */
            mode: string;
            /** Model */
            model: {
                [key: string]: unknown;
            };
            /** Not Ranked Reasons */
            not_ranked_reasons: string[];
            /** Pack */
            pack: {
                [key: string]: unknown;
            };
            profile: components["schemas"]["Profile"];
            /** Provider */
            provider: string;
            /** Ranked */
            ranked: boolean;
            /** Repetitions */
            repetitions: number;
            /** Track */
            track: string;
        };
        /** RunSummary */
        RunSummary: {
            /** Completed At */
            completed_at: string | null;
            /** Concurrency */
            concurrency: number;
            consistency: components["schemas"]["Consistency"];
            cost: components["schemas"]["CostSummary"];
            /** Created At */
            created_at: string;
            /** Endpoint */
            endpoint: string | null;
            /** Fingerprint */
            fingerprint: string;
            /** Ineligible Reasons */
            ineligible_reasons: string[];
            /** Is Mock */
            is_mock: boolean;
            /** Last Event Id */
            last_event_id: number;
            latency_ms: components["schemas"]["LatencySummary"];
            /** Leaderboard Eligible */
            leaderboard_eligible: boolean;
            /** Mode */
            mode: string;
            /** Model Id */
            model_id: string;
            /** Model Meta */
            model_meta: {
                [key: string]: unknown;
            };
            /** Not Ranked Reasons */
            not_ranked_reasons: string[];
            /** Pack Hash */
            pack_hash: string;
            /** Pack Id */
            pack_id: string;
            profile: components["schemas"]["Profile"];
            /** Profile Id */
            profile_id: string;
            /** Provider */
            provider: string;
            /** Ranked */
            ranked: boolean;
            /** Repetitions */
            repetitions: number;
            /** Request */
            request: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            scores: components["schemas"]["ScoreSummary"];
            /** State */
            state: string;
            /** State Reason */
            state_reason: string | null;
            /** Suite Version */
            suite_version: string;
            /** Track */
            track: string;
            /** Updated At */
            updated_at: string;
            usage: components["schemas"]["UsageSummary"];
            /** Versions */
            versions: {
                [key: string]: string;
            };
        };
        /** ScoreSummary */
        ScoreSummary: {
            /** Aggregation Version */
            aggregation_version: string;
            /** Categories */
            categories: {
                [key: string]: number;
            };
            /** Completed */
            completed: number;
            /** Conditional Quality */
            conditional_quality: number | null;
            /** Instances */
            instances: number;
            /** Interval 95 */
            interval_95: number[] | null;
            /** Official */
            official: boolean;
            /** Optimal Rate */
            optimal_rate: number | null;
            /** Overall */
            overall: number | null;
            /** Provisional Overall */
            provisional_overall: number | null;
            /** Scheduled */
            scheduled: number;
            /** States */
            states: {
                [key: string]: number;
            };
            /** Tiers */
            tiers: {
                [key: string]: number;
            };
            /** Valid Rate */
            valid_rate: number | null;
        };
        /** SnapshotInfo */
        SnapshotInfo: {
            /** Fetched At */
            fetched_at: string;
            /** Model Count */
            model_count: number;
            /** Snapshot Id */
            snapshot_id: number;
            /** Stale */
            stale: boolean;
        };
        /** UsageSummary */
        UsageSummary: {
            /** Attempts */
            attempts: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Reasoning Tokens */
            reasoning_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_backup_api_admin_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admin_workers_api_admin_workers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_catalog_api_catalog_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_endpoints_api_catalog_endpoints_get: {
        parameters: {
            query: {
                model_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Endpoints"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_catalog_api_catalog_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    put_favorite_api_favorites_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_instance_api_instances__instance_id__get: {
        parameters: {
            query?: {
                reveal?: boolean;
            };
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_api_instances__instance_id__replay_get: {
        parameters: {
            query?: {
                run_id?: string | null;
                job_id?: number | null;
            };
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_leaderboard_get: {
        parameters: {
            query?: {
                track?: string;
                profile_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    get_model_detail_api_models_detail_get: {
        parameters: {
            query: {
                model_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_packs_api_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackSummary"][];
                };
            };
        };
    };
    get_pack_api_packs__pack_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practice_api_practice_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSummary"][];
                };
            };
        };
    };
    practice_submit_api_practice__instance_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"][];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                model_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimate_run_api_runs_estimate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_action_api_runs__run_id__actions__action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_api_runs__run_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_items_api_runs__run_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_runs__run_id__items__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reevaluate_run_api_runs__run_id__reevaluate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
